---
- name: Ensure the directory {{ kube_admission_configs_path }} is exists
  file:
    dest: '{{ kube_admission_configs_path }}'
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Copy audit policy config
  copy:
    src: audit-policy.yaml
    dest: '{{ kube_apiserver_audit.policy_file }}'
    owner: root
    group: root
    mode: 0640
  when: kube_apiserver_audit is defined

- name: Render control-config
  template:
    src: control-config.yaml.j2
    dest: '{{ kube_admission_configs_path }}/control-config.yaml'
    owner: root
    group: root
    mode: 0640
  when: '"EventRateLimit" in kube_admission_plugins or "PodNodeSelector" in kube_admission_plugins and pod_node_selector_file'

- name: Copy event-rate-limit config
  copy:
    src: event-rate-limit.yaml
    dest: '{{ kube_admission_configs_path }}/event-rate-limit.yaml'
    owner: root
    group: root
    mode: 0640
  when: '"EventRateLimit" in kube_admission_plugins'

- name: Copy pod-node-selector config
  copy:
    src: pod-node-selector.yaml
    dest: '{{ kube_admission_configs_path }}/pod-node-selector.yaml'
    owner: root
    group: root
    mode: 0640
  when:
    - '"PodNodeSelector" in kube_admission_plugins'
    - pod_node_selector_file
