apiVersion: v1
data:
  auto-direct-node-routes: "true"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cilium-endpoint-gc-interval: 5m0s
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.233.64.0/18
  cluster-pool-ipv4-mask-size: "24"
  cni-chaining-mode: portmap
  custom-cni-conf: "false"
  debug: "false"
  devices: enp0s8
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "false"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-reachable-services: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-l7-proxy: "false"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "false"
  ipam: cluster-pool
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  masquerade: "false"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  native-routing-cidr: 10.233.0.0/16
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: disabled
  wait-bpf-mount: "false"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2021-01-11T10:22:31Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:auto-direct-node-routes: {}
        f:bpf-lb-map-max: {}
        f:bpf-map-dynamic-size-ratio: {}
        f:bpf-policy-map-max: {}
        f:cilium-endpoint-gc-interval: {}
        f:cluster-name: {}
        f:cluster-pool-ipv4-mask-size: {}
        f:cni-chaining-mode: {}
        f:custom-cni-conf: {}
        f:debug: {}
        f:disable-cnp-status-updates: {}
        f:enable-auto-protect-node-port-range: {}
        f:enable-bandwidth-manager: {}
        f:enable-bpf-clock-probe: {}
        f:enable-endpoint-health-checking: {}
        f:enable-health-check-nodeport: {}
        f:enable-health-checking: {}
        f:enable-host-reachable-services: {}
        f:enable-hubble: {}
        f:enable-ipv4: {}
        f:enable-ipv6: {}
        f:enable-local-redirect-policy: {}
        f:enable-policy: {}
        f:enable-remote-node-identity: {}
        f:enable-session-affinity: {}
        f:enable-well-known-identities: {}
        f:enable-xt-socket-fallback: {}
        f:hubble-disable-tls: {}
        f:hubble-listen-address: {}
        f:hubble-socket-path: {}
        f:hubble-tls-cert-file: {}
        f:hubble-tls-client-ca-files: {}
        f:hubble-tls-key-file: {}
        f:identity-allocation-mode: {}
        f:ipam: {}
        f:kube-proxy-replacement: {}
        f:kube-proxy-replacement-healthz-bind-address: {}
        f:monitor-aggregation: {}
        f:monitor-aggregation-flags: {}
        f:monitor-aggregation-interval: {}
        f:node-port-bind-protection: {}
        f:operator-api-serve-addr: {}
        f:preallocate-bpf-maps: {}
        f:sidecar-istio-proxy-image: {}
        f:tunnel: {}
        f:wait-bpf-mount: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
    manager: Go-http-client
    operation: Update
    time: "2021-01-11T10:22:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:cluster-pool-ipv4-cidr: {}
        f:devices: {}
        f:enable-bpf-masquerade: {}
        f:enable-endpoint-routes: {}
        f:enable-l7-proxy: {}
        f:install-iptables-rules: {}
        f:masquerade: {}
        f:native-routing-cidr: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-01-11T11:34:01Z"
  name: cilium-config
  namespace: kube-system
  resourceVersion: "13455"
  uid: 5a2d3151-0c50-4923-8ced-714fc3205585
