---
kubeconfig_path_remote: /etc/kubernetes/admin.conf
kubeconfig_path_local: '{{ artifacts_dir }}/kubeconfig'

kube_network_plugin: cilium
kube_network_service_subnet: 10.233.0.0/18
kube_network_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24

kube_cluster_name: default
kube_cluster_dns_domain: cluster.local
kube_cluster_dns_ip: '{{ kube_network_service_subnet | ipaddr("net") | ipaddr(10) | ipaddr("address") }}'

kubelet_reserved_system_cpus: 0

# kube_load_balancer_addr: 10.20.30.40:6443
kube_apiserver_port: 6443
kube_control_plain_endpoint: >-
  {%- if kube_load_balancer_addr is defined -%}
  {{ kube_load_balancer_addr }}
  {%- else -%}
  {{ hostvars[groups["k8s-master"][0]].ansible_default_ipv4.address }}:{{ kube_apiserver_port }}
  {%- endif -%}

kube_bin_dir: /usr/local/bin
kube_cni_bin_dir: /usr/lib/cni
kube_cni_conf_dir: /etc/cni/net.d
