---
# tasks file for cilium
- name: Add cilium chart repo
  community.kubernetes.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install Cilium into Kubernetes cluster
  community.kubernetes.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: '{{ cilium_chart_version }}'
    release_namespace: kube-system
    values: '{{ lookup("template", "values.yml.j2") | from_yaml }}'
    kubeconfig_path: '{{ kubeconfig_path_local }}'
    atomic: yes
    wait: yes
    wait_timeout: 120s
