---
- name: Add prometheus-community chart repo
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install kube-prometheus-stack into Kubernetes cluster
  community.kubernetes.helm:
    name: prom
    chart_ref: prometheus-community/kube-prometheus-stack
    create_namespace: yes
    release_namespace: '{{ prometheus_stack_namespace }}'
    values: '{{ lookup("file", "values.yaml") | from_yaml }}'
    kubeconfig_path: '{{ kubeconfig_path_local }}'
    atomic: yes
    wait: yes
    wait_timeout: 120s
