- name: Add {{ prometheus_stack_chart_repo_name }} chart repo
  community.kubernetes.helm_repository:
    name: '{{ prometheus_stack_chart_repo_name }}'
    repo_url: '{{ prometheus_stack_chart_repo_url }}'

- name: Install {{ prometheus_stack_release_name }} into Kubernetes cluster
  community.kubernetes.helm:
    name: '{{ prometheus_stack_release_name }}'
    chart_ref: '{{ prometheus_stack_chart_repo_name }}/kube-prometheus-stack'
    chart_version: '{{ prometheus_stack_chart_version }}'
    release_namespace: '{{ prometheus_stack_namespace }}'
    create_namespace: yes
    values: '{{ lookup("template", "values.yml.j2") | from_yaml }}'
    kubeconfig_path: '{{ kubeconfig_path_local }}'
    atomic: yes
    wait: yes
    wait_timeout: 120s

- name: Render additional dashboards
  template:
    src: dashboards.yaml.j2
    dest: '{{ artifacts_dir }}/dashboards.yaml'
    mode: 0644

- name: Add Grafana dashboards
  command: >-
    kubectl
    --kubeconfig={{ kubeconfig_path_local }}
    --namespace={{ prometheus_stack_namespace }}
    apply -f {{ artifacts_dir }}/dashboards.yaml
