---
- name: Create kubeadm token for joining worker node with 10m expiration
  kubeadm:
    kubeadm_bin: '{{ bin_dir }}/kubeadm'
    token:
      create:
        ttl: 10m
  run_once: true
  register: temp_token
  delegate_to: '{{ kube_cluster_initialzed_master[0] }}'
  when: kubeadm_token is not defined and kube_cluster_is_initialzed
  tags:
    - join_worker

- name: Set kubeadm_token to generated token
  set_fact:
    kubeadm_token: '{{ temp_token.stdout }}'
  delegate_to: '{{ item }}'
  delegate_facts: True
  with_items: '{{ groups["k8s-worker"] }}'
  when: '"stdout" in temp_token'
  tags:
    - join_worker

- name: Render join kubeconfig
  template:
    src: kubeadm-config-join.yaml.j2
    dest: '{{ kubeadm_config_file_path }}'
    owner: root
    group: root
    mode: 0600
  when: not kubelet_already_running
  tags:
    - join_worker

- name: Join worker node to the cluster
  kubeadm:
    kubeadm_bin: '{{ bin_dir }}/kubeadm'
    join:
      kubeadm_config: '{{ kubeadm_config_file_path }}'
  environment:
    PATH: '{{ bin_dir }}:{{ ansible_env.PATH }}'
  register: kubeadm_join_control_plane
  when: not kubelet_already_running
  tags:
    - join_worker

- name: Render kubelet.conf
  template:
    src: kubelet.conf.j2
    dest: /etc/kubernetes/kubelet.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart kubelet
  when: groups["k8s-master"] | length > 1
  tags:
    - join_worker

- name: Prepare roles
  set_fact:
    roles: >-
      [{%- if hostvars[inventory_hostname].roles is defined -%}
      {% for role in hostvars[inventory_hostname].roles.split(',') %}
      'node-role.kubernetes.io/{{ role }}=',
      {% endfor %}
      {%- else -%}
      'node-role.kubernetes.io/worker=',
      {%- endif -%}]
  tags:
    - join_worker
    - set_roles

- name: Set roles on worker node
  kubectl:
    set_labels: yes
    resource: node
    name: "{% if kube_rewrite_nodename %}{{ inventory_hostname }}{% else %}{{ hostvars[inventory_hostname].ansible_hostname }}{% endif %}"
    labels: '{{ roles }}'
    state: latest
  delegate_to: '{{ kube_cluster_initialzed_master[0] }}'
  tags:
    - join_worker
    - set_roles
