#!/usr/bin/env -S ansible-playbook
- hosts: k8s-worker
  gather_facts: no
  handlers:
    - name: Restart kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: restarted
  tasks:
    - name: Add haproxy manifest
      block:
        - name: Ensure the directories is exists
          file:
            dest: '{{ item }}'
            state: directory
            owner: root
            group: root
            mode: 0750
          with_items:
            - '{{ haproxy_config_dir }}'
            - '{{ kube_manifest_dir }}'

        - name: Create haproxy config directory
          file:
            path: '{{ haproxy_config_dir }}'
            state: directory
            owner: root
            group: root
            mode: 0750

        - name: Render {{ haproxy_config_dir }}/haproxy.cfg
          template:
            src: haproxy.cfg.j2
            dest: '{{ haproxy_config_dir }}/haproxy.cfg'
            owner: root
            group: root
            mode: 0640

        - name: Get checksum of config
          stat:
            path: '{{ haproxy_config_dir }}/haproxy.cfg'
          register: haproxy_stat

        - name: Render haproxy static pod manifest
          template:
            src: haproxy.manifest.yaml.j2
            dest: '{{ kube_manifest_dir }}/haproxy.yaml'

        - name: Render kubelet.conf
          template:
            src: kubelet.conf.j2
            dest: /etc/kubernetes/kubelet.conf
            owner: root
            group: root
            mode: 0600
          notify: Restart kubelet
      when:
        - kube_load_balancer_addr is not defined or (kube_load_balancer_addr is defined and kube_load_balancer_addr.split(":")[0] not in ["127.0.0.1", "localhost"])
        - groups["k8s-master"] | length > 1
