#!/usr/bin/env -S ansible-playbook
- hosts: k8s-master
  gather_facts: no
  tasks:
    - name: Fetch kubeconfig to {{ artifacts_dir }}
      ansible.builtin.fetch:
        src: '{{ kubeconfig_path_remote }}'
        dest: '{{ kubeconfig_path_local }}'
        mode: 0600
        flat: yes
      run_once: yes
