
- hosts: k8s-master
  tasks:
    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: '{{ kubeconfig_path }}'
        dest: '{{ kubeconfig_file_path_local }}'
        mode: 0600
        flat: yes
      run_once: yes
