
- hosts: k8s-master
  tasks:
    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: '{{ kubeconfig_path }}'
        dest: '{{ inventory_dir }}/artifacts/kubeconfig'
        mode: 0600
        flat: yes
      run_once: yes
