#!/usr/bin/env -S ansible-playbook
- import_playbook: '{{ playbook_dir }}/../system/setup.yml'
- import_playbook: facts.yml

- hosts: k8s-master
  gather_facts: no
  tasks:
    - name: Init first node of Kubernetes cluster
      block:
        - name: Generate kubeadm token
          set_fact:
            kubeadm_token: '{{ lookup("password", "/dev/null chars=ascii_lowercase,digits length=6") }}.{{ lookup("password", "/dev/null chars=ascii_lowercase,digits length=16") }}'

        - name: Render init kubeconfig
          template:
            src: kubeadm-config-init.yaml.j2
            dest: '{{ kubeadm_config_path }}'
            owner: root
            group: root
            mode: 0600

        - name: Init first Kubernetes node {% if kubeadm_init_phases_skip %}with skip phases {{ kubeadm_init_phases_skip | join(",") }}{% endif %}
          command: >-
            kubeadm init
            --upload-certs
            --config={{ kubeadm_config_path }}
            {% if kubeadm_init_phases_skip %} --skip-phases={{ kubeadm_init_phases_skip | join(",") }}{% endif %}
      run_once: yes
      when: not kubelet_already_running

- import_playbook: fetch_kubeconfig.yml
- import_playbook: psp.yml
  when: kube_pod_security_policy_enable

- import_playbook: cilium.yml
  when: kube_network_plugin == "cilium"

- import_playbook: node_join.yml
