#!/usr/bin/env -S ansible-playbook
- hosts: k8s
  gather_facts: no
  handlers:
    - name: Restart systemd-timesyncd
      systemd:
        name: systemd-timesyncd
        enabled: yes
        daemon_reload: yes
        state: restarted
  tasks:
    - name: Render timesync config
      template:
        src: timesyncd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        owner: root
        group: root
        mode: 0644
      when: ntp_servers is defined and ntp_servers
      notify: Restart systemd-timesyncd
