- hosts: k8s
  gather_facts: yes
  tasks:
    - name: Update apt cache and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      when: ansible_os_family == "Debian"
