---
# defaults file for cilium
cilium_wait_agent_after_deploy: true

cilium_chart_version: v1.9.6
cilium_version: v1.9.6
cilium_hubble_ui_version: v0.7.3
cilium_hubble_ui_envoy_version: v1.18.2@sha256:e8b37c1d75787dd1e712ff389b0d37337dc8a174a63bed9c34ba73359dc67da7

cilium_image_repository: quay.io/cilium/cilium
cilium_image_operator_repository: quay.io/cilium/operator
cilium_image_hubble_relay_repository: quay.io/cilium/hubble-relay
cilium_image_hubble_ui_repository: quay.io/cilium/hubble-ui
cilium_image_hubble_ui_backend_repository: quay.io/cilium/hubble-ui-backend
cilium_image_envoy_repository: docker.io/envoyproxy/envoy
cilium_operator_replicas: 2

cilium_agent_rollout_pods: false

cilium_operator_enabled: true
cilium_operator_rollout_pods: false

cilium_hubble_enabled: false
cilium_hubble_ui_enabled: false
cilium_hubble_ui_relay_enabled: false
cilium_hubble_ui_ingress_enabled: false
cilium_hubble_ui_ingress_host:
  - chart-example.local
cilium_hubble_ui_ingress_annotations: {}
cilium_hubble_ui_ingress_tls: []
## --enable-bpf-masquerade  | Masquerade packets from endpoints leaving the host with BPF instead of iptables
cilium_bpf_enable_masquerade: true
## --preallocate-bpf-maps | Enable BPF map pre-allocation
cilium_bpf_preallocate_maps: false
## --kube-proxy-replacement | auto-enable available features for kube-proxy replacement ("probe"),
##   or enable only selected features (will panic if any selected feature cannot be enabled) ("partial")
##   or enable all features (will panic if any feature cannot be enabled) ("strict"), or completely disable
##   it (ignores any selected feature) ("disabled") (default "partial")
cilium_kube_proxy_replacement: strict
## --tunnel string  | Tunnel mode {vxlan, geneve, disabled} (default "vxlan" for the "veth" datapath mode)
cilium_tunnel: vxlan
## --bpf-lb-mode  | BPF load balancing mode ("snat", "dsr", "hybrid")
cilium_load_balancer_mode: snat
## --bpf-lb-algorithm | BPF load balancing algorithm ("random", "maglev")
cilium_load_balancer_algorithm: maglev
## https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#maglev-consistent-hashing-beta
## --bpf-lb-maglev-table-size | Maglev per service backend table size
# cilium_maglev_table_size: 16381
## --bpf-lb-maglev-hash-seed | Maglev cluster-wide hash seed (base64 encoded)
# cilium_maglev_hash_seed: qt2OmdVabSzl7t4e
## --auto-direct-node-routes  | Enable automatic L2 routing between nodes
cilium_auto_direct_node_routes: false
## Install the CNI configuration and binary files into the filesystem
cilium_cni_install: true
## Skip writing of the CNI configuration. This can be used if writing of the CNI configuration is performed by external automation
cilium_cni_custom_conf: false
## ??? Not in cmdref: --cni-chaining-mode | Possible values: "none", "generic-veth", "aws-cni", "portmap"
cilium_cni_chaining_mode: portmap
## --enable-bandwidth-manager | Enable BPF bandwidth manager
cilium_bandwidth_manager: false
## --enable-host-port | Enable k8s hostPort mapping feature (requires enabling enable-node-port)
cilium_host_port: false
## --enable-node-port | Enable NodePort type services by Cilium
cilium_node_port: false
## --enable-host-reachable-services | Enable reachability of services for host applications
cilium_host_services: false
## --enable-external-ips  | Enable k8s service externalIPs feature (requires enabling enable-node-port)
cilium_enable_external_ips: false
## --devices  | List of devices facing cluster/external network (used for BPF NodePort, BPF masquerading and host firewall)
cilium_devices: []
## --enable-endpoint-routes | Use per endpoint routes instead of routing via cilium_host
cilium_enable_endpoint_routes: true
## --enable-l7-proxy  | Enable L7 proxy for L7 policy enforcement
cilium_enable_l7_proxy: true
## --enable-local-redirect-policy | Enable Local Redirect Policy
cilium_local_redirect_policy: true
## --enable-policy  | Enable policy enforcement (default "default")
cilium_policy_enforcement_mode: default
## --native-routing-cidr  | Allows to explicitly specify the CIDR for native routing. This value corresponds to the configured cluster-cidr.
cilium_native_routing_cidr: '{{ kube_network_pods_subnet | default("10.0.0.0/8") }}'
cilium_bpf_host_routing: true
cilium_enable_ipv4_masquerade: true

#### Operator
## --cluster-pool-ipv4-cidr | IPv4 CIDR Range for Pods in cluster. Requires 'ipam=cluster-pool' and 'enable-ipv4=true'
cilium_cluster_pool_ipv4_pod_cidr: '{{ kube_network_pods_subnet | default("10.0.0.0/8") }}'
## --cluster-pool-ipv4-mask-size | Mask size for each IPv4 podCIDR per node. Requires 'ipam=cluster-pool' and 'enable-ipv4=true' (default 24)
cilium_cluster_pool_ipv4_mask_size: '{{ kube_network_node_prefix | default(24) }}'

## cilium-agent Daemonset configuration. Possible values: "containerd", "crio", "docker", "none", "auto"
cilium_cri_integration: none
cilium_cri_socket: '{{ cri_socket | default("") }}'
cilium_masquerade: true

## ETCD
# cilium_cluster_domain: '{{ kube_cluster_dns_domain | default("default") }}'

## ref: https://docs.cilium.io/en/stable/concepts/networking/ipam/
## --ipam | Backend to use for IPAM (default "cluster-pool")
cilium_ipam_mode: cluster-pool
