---
- name: Create kubeadm token for joining master node with 10m expiration
  kubeadm:
    kubeadm_bin: '{{ bin_dir }}/kubeadm'
    token:
      create:
        ttl: 10m
        certificate_key: '{{ kubeadm_certificate_key }}'
  run_once: true
  register: temp_token
  delegate_to: '{{ kube_cluster_initialzed_master[0] }}'
  when: kubeadm_token is not defined and kube_cluster_is_initialzed

- name: Set kubeadm_token for each node
  set_fact:
    kubeadm_token: '{{ temp_token.stdout }}'
  delegate_to: '{{ item }}'
  delegate_facts: True
  with_items: '{{ groups["k8s"] }}'
  when: '"stdout" in temp_token'

- name: Render join kubeconfig
  template:
    src: kubeadm-config-join.yaml.j2
    dest: '{{ kubeadm_config_file_path }}'
    owner: root
    group: root
    mode: 0600

- name: Join master to the cluster
  kubeadm:
    kubeadm_bin: '{{ bin_dir }}/kubeadm'
    join:
      kubeadm_config: '{{ kubeadm_config_file_path }}'
  environment:
    PATH: '{{ bin_dir }}:{{ ansible_env.PATH }}'

- name: Update kubeconfig for root user
  include_tasks: kubeconfig.yml
