---
- name: Create .kube in root home
  file:
    path: /root/.kube
    state: directory
  tags:
    - kubeconfig
    - join_master

- name: Copy kubernetes admin.conf to root home dir
  copy:
    src: '{{ kube_config }}'
    dest: /root/.kube/config
    mode: 0600
    remote_src: yes
  tags:
    - kubeconfig
    - join_master
