---
- name: Add Cilium chart repo
  community.kubernetes.helm_repository:
    binary_path: '{{ bin_dir }}/helm'
    name: cilium
    repo_url: https://helm.cilium.io/
  tags: network

- name: Deploy cilium into Kubernetes cluster
  community.kubernetes.helm:
    binary_path: '{{ bin_dir }}/helm'
    name: cilium
    chart_ref: cilium/cilium
    chart_version: '{{ cilium_version }}'
    release_namespace: kube-system
    values: '{{ lookup("template", "cilium.values.yml.j2") | from_yaml }}'
    kubeconfig_path: '{{ kube_config }}'
  tags: network

- name: Wait for pods to run
  command: "{{ bin_dir }}/kubectl -n kube-system get pods -l k8s-app=cilium -o jsonpath='{.items[?(@.status.containerStatuses[0].ready==true)].metadata.name}'"
  register: pods_not_ready
  changed_when: false
  until: '"cilium" in pods_not_ready.stdout'
  retries: 30
  delay: 10
  ignore_errors: yes
  tags: network
