---
cri_socket: /run/containerd/containerd.sock
registry_mirrors: {}
  # docker.io: ["host1", "host2"]

kube_version: v1.20.2
crictl_version: v1.20.0

kube_rewrite_nodename: true
kube_manifest_dir: /etc/kubernetes/manifests
# kube_node_max_pods: 110
# kube_tls_min_version: VersionTLS12

kubeadm_config_path: /root/kubeadmconfig.yaml
kube_apiserver_anonymous_auth_disable: false

kube_profiling: false
kube_tls_cipher_suites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_RSA_WITH_AES_128_GCM_SHA256
  - TLS_RSA_WITH_AES_256_GCM_SHA384
