#!/usr/bin/env -S ansible-playbook
- hosts: workstation
  gather_facts: no
  tasks:
    - name: Set Ansible Python interpreter variable
      set_fact:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
      when: ansible_python_interpreter is not defined or ansible_python_interpreter != ansible_playbook_python
