---
- name: Create {{ cache_tmp_dir }} directory
  file:
    path: '{{ cache_tmp_dir }}'
    state: directory
    mode: 0755

- name: Render {{ cache_server_systemd_unit }} configs
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0640
  with_items:
    - {'src': "http-pyserver.env.j2", 'dest': '/etc/{{ default_configs_dir_name }}/{{ cache_server_systemd_unit }}'}
    - {'src': "http-pyserver.service.j2", 'dest': '/etc/systemd/system/{{ cache_server_systemd_unit }}.service'}

- name: Download Kubernetes binaries to cache {{ cache_tmp_dir }}
  get_url:
    url: '{{ item.url }}'
    dest: '{{ cache_tmp_dir }}/{{ item.url | basename }}'
    mode: 0444
    checksum: '{{ item.checksum }}'
  register: result
  until: result is succeeded
  retries: 3
  delay: 5
  with_items: '{{ cache_download_list + cache_download_list_extend }}'

- name: Start cache server
  systemd:
    name: '{{ cache_server_systemd_unit }}'
    enabled: no
    state: started
