---
crictl_version: v1.20.0
cri_socket: /run/containerd/containerd.sock
registry_mirrors: {}
  # docker.io: ["host1", "host2"]

kubeadm_config_path: /root/kubeadmconfig.yaml
kubeadm_init_phases_skip: [ "addon/kube-proxy" ]


## Kubernetes configs
### K8s paths
kubeconfig_path_local: '{{ artifacts_dir }}/kubeconfig'

kube_dir: /etc/kubernetes
kubeconfig_path_remote: '{{ kube_dir }}/admin.conf'
kube_manifest_dir: '{{ kube_dir }}/manifests'
kube_admission_configs_path: '{{ kube_dir }}/admission-configs'

kube_bin_dir: /usr/local/bin
kube_cni_bin_dir: /usr/lib/cni
kube_cni_conf_dir: /etc/cni/net.d

### Cluster configuration
kube_version: v1.20.6
kube_rewrite_nodename: true
# kube_image_repository: k8s.gcr.io

# kube_load_balancer_addr: 10.20.30.40:6443
kube_apiserver_port: 6443
# kube_apiserver_logs_path: /var/log/kube/apiserver
# kube_apiserver_audit:
#   policy_file: '{{ kube_admission_configs_path }}/audit-policy.yaml'
#   log_maxage: 30
#   log_maxbackup: 3
#   log_maxsize: 100
#   log_path: '{{ kube_apiserver_logs_path }}/audit.log'
#   webhook:
#     config_file: '{{ kube_admission_configs_path }}/webhook-config.yaml'
#     mode: ""
#     batch_max_size: ""
#     batch_max_wait: ""

# kube_tls_min_version: VersionTLS12
kube_tls_cipher_suites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_RSA_WITH_AES_128_GCM_SHA256
  - TLS_RSA_WITH_AES_256_GCM_SHA384
kube_admission_plugins: []
kube_profiling: false

kube_network_plugin: cilium
kube_network_service_subnet: 10.233.0.0/18
kube_network_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24

kube_cluster_name: default
kube_cluster_dns_domain: cluster.local

# kube_controller_manager_bind_address: 0.0.0.0
# kube_scheduler_bind_address: 0.0.0.0

#### Kubelet configuration
# kubelet_reserved_system_cpus: 0
# kubelet_cpu_reserved: 250m
# kubelet_memory_reserved: 256Mi
# kubelet_bind_address: 0.0.0.0
# kubelet_node_max_pods: 110

kube_control_plain_endpoint: >-
  {%- if kube_load_balancer_addr is defined -%}
  {{ kube_load_balancer_addr }}
  {%- else -%}
  {{ hostvars[groups["k8s-master"][0]].ansible_default_ipv4.address }}:{{ kube_apiserver_port }}
  {%- endif -%}

keepalived_enabled: false
